### ISSUE TITLE
Error when updating external scenario

### ISSUE THREAD

**Issue by marcosdbw** [premise-community-scenarios/ammonia-prospective-scenarios#1] opened 2022-10-20 14:39 UTC
Hello, 
I was testing the ammonia scenarios using ecoinvent 3.8, however, I could not create and write the database because of this error.
@romainsacchi , do you know how I can solve it?
Thanks a lot. 

//////////////// IMPORTING USER-DEFINED INVENTORIES ////////////////
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)

----> 3 ndb.update_all()

   (...)

File ~\Miniconda3\envs\bw2\lib\site-packages\premise\ecoinvent_modification.py:986, in NewDatabase.update_all(self)
    984 self.update_steel()
    985 self.update_fuels()
--> 986 self.update_external_scenario()

File ~\Miniconda3\envs\bw2\lib\site-packages\premise\ecoinvent_modification.py:915, in NewDatabase.update_external_scenario(self)
    913 for d, datapackage in enumerate(self.datapackages):
    914     if "inventories" in [r.name for r in datapackage.resources]:
--> 915         inventories = self.__import_additional_inventories(
    916             datapackage
    917         )
    918     else:
    919         inventories = []

File ~\Miniconda3\envs\bw2\lib\site-packages\premise\ecoinvent_modification.py:721, in NewDatabase.__import_additional_inventories(self, datapackage)
    718 data = []
    720 if datapackage.get_resource("inventories"):
--> 721     additional = AdditionalInventory(
    722         database=self.database,
    723         version_in=datapackage.descriptor["ecoinvent"]["version"],
    724         version_out=self.version,
    725         path=datapackage.get_resource("inventories").source,
    726     )
    727     additional.prepare_inventory()
    728     data.extend(additional.merge_inventory())

File ~\Miniconda3\envs\bw2\lib\site-packages\premise\inventory_imports.py:530, in AdditionalInventory.__init__(self, database, version_in, version_out, path)
    529 def __init__(self, database, version_in, version_out, path):
--> 530     super().__init__(database, version_in, version_out, path)

File ~\Miniconda3\envs\bw2\lib\site-packages\premise\inventory_imports.py:131, in BaseInventoryImport.__init__(self, database, version_in, version_out, path)
    125         raise FileNotFoundError(
    126             f"The inventory file {path} could not be found."
    127         )
    129 self.path = path
--> 131 self.import_db = self.load_inventory(path)
    133 # register migration maps
    134 # as imported inventories link to different ecoinvent versions
    135 ei_versions = ["35", "36", "37", "38"]

File ~\Miniconda3\envs\bw2\lib\site-packages\premise\inventory_imports.py:553, in AdditionalInventory.load_inventory(self, path)
    551     return ExcelImporter(path)
    552 elif Path(path).suffix == ".csv":
--> 553     return CSVImporter(path)
    554 else:
    555     raise ValueError(
    556         "Incorrect filetype for inventories." "Should be either .xlsx or .csv"
    557     )

File ~\Miniconda3\envs\bw2\lib\site-packages\bw2io\importers\excel.py:107, in ExcelImporter.__init__(self, filepath)
    105 start = time()
    106 data = self.extractor.extract(filepath)
--> 107 data = [(x, y) for x, y in data if valid_first_cell(x, y)]
    108 print(
    109     "Extracted {} worksheets in {:.2f} seconds".format(
    110         len(data), time() - start
    111     )
    112 )
    113 if data and any(line for line in data):

File ~\Miniconda3\envs\bw2\lib\site-packages\bw2io\importers\excel.py:107, in <listcomp>(.0)
    105 start = time()
    106 data = self.extractor.extract(filepath)
--> 107 data = [(x, y) for x, y in data if valid_first_cell(x, y)]
    108 print(
    109     "Extracted {} worksheets in {:.2f} seconds".format(
    110         len(data), time() - start
    111     )
    112 )
    113 if data and any(line for line in data):

ValueError: too many values to unpack (expected 2)

**Comment by romainsacchi** [comment] 2022-10-20 14:42
Yes, I've seen that issue before.

Can you try to uninstall `bw2io` and re-install it doing:
`git+https://github.com/brightway-lca/brightway2-io.git`

**Comment by romainsacchi** [comment] 2022-10-20 14:43
Before, can you tell me which `bw2io` version you had?

**Comment by marcosdbw** [comment] 2022-10-20 15:03
version 0.8.6
I did not see your message and updated it to 0.8.8

**Comment by marcosdbw** [comment] 2022-10-20 15:40
I got the same error message even after updating bw2io

**Comment by romainsacchi** [comment] 2022-10-21 08:49
So, you're still having the issue with `bw2io 0.8.8`?
Stupid question, but have you restarted the kernel of your notebook after the update?

**Comment by marcosdbw** [comment] 2022-10-21 08:50
Thanks @romainsacchi , I think the bw2io problem was solved when I updated it to 0.9.dev10 

The error that I see now is related to 'No efficiency factor provided for region RER' 

ile ~\Miniconda3\envs\bw2\lib\site-packages\premise\ecoinvent_modification.py:986, in NewDatabase.update_all(self)
    984 self.update_steel()
    985 self.update_fuels()
--> 986 self.update_external_scenario()

File ~\Miniconda3\envs\bw2\lib\site-packages\premise\ecoinvent_modification.py:934, in NewDatabase.update_external_scenario(self)
    931     scenario["database"] = checked_database
    932     scenario["database"].extend(checked_inventories)
--> 934 external_scenario = ExternalScenario(
    935     database=scenario["database"],
    936     model=scenario["model"],
    937     pathway=scenario["pathway"],
    938     iam_data=scenario["iam data"],
    939     year=scenario["year"],
    940     external_scenarios=self.datapackages,
    941     external_scenarios_data=scenario["external data"],
    942 )
    943 external_scenario.create_custom_markets()
    944 scenario["database"] = external_scenario.database

File ~\Miniconda3\envs\bw2\lib\site-packages\premise\external.py:326, in ExternalScenario.__init__(self, database, iam_data, external_scenarios, external_scenarios_data, model, pathway, year)
    324     config_file = yaml.safe_load(resource.raw_read())
    325     ds_names = get_recursively(config_file, "name")
--> 326     self.regionalize_inventories(ds_names, external_scenario_regions)
    327 self.dict_bio_flows = get_biosphere_flow_uuid()

File ~\Miniconda3\envs\bw2\lib\site-packages\premise\external.py:390, in ExternalScenario.regionalize_inventories(self, ds_names, regions)
    384 # adjust efficiency of datasets
    385 for dataset in ws.get_many(
    386     self.database,
    387     ws.equals("adjust efficiency", True),
    388     ws.either(*[ws.contains("name", name) for name in ds_names]),
    389 ):
--> 390     adjust_efficiency(dataset)
    391     del dataset["adjust efficiency"]

File ~\Miniconda3\envs\bw2\lib\site-packages\premise\external.py:208, in adjust_efficiency(dataset)
    206     except KeyError as err:
    207         print(dataset["name"], dataset["location"], dataset["regions"])
--> 208         raise KeyError(
    209             f"No efficiency factor provided for region {dataset['location']}"
    210         ) from err
    211 else:
    212     scaling_factor = 1 / v[1].get(dataset["regions"][0], 1)

KeyError: 'No efficiency factor provided for region RER'

**Comment by romainsacchi** [comment] 2022-10-21 08:51
Good.
Can you check the premise version? It should be 1.3.2.

**Comment by marcosdbw** [comment] 2022-10-21 08:52
Yes, it is 1.3.2

**Comment by romainsacchi** [comment] 2022-10-21 08:54
Do you mind printing your script? (scenarios, years, and premise functions ran)
I'll try to reproduce that.

**Comment by marcosdbw** [comment] 2022-10-21 08:57
Sure, here it is:

import brightway2 as bw
from premise import NewDatabase
from datapackage import Package
    
    
    fp = r"https://raw.githubusercontent.com/premise-community-scenarios/ammonia-prospective-scenarios/main/datapackage.json"
    ammonia = Package(fp)
    
    bw.projects.set_current("newPremise")
    
    ndb = NewDatabase(
            scenarios = [
                {"model":"remind", "pathway":"SSP2-PkBudg1150", "year":2050,},
            ],        
            source_db="ecoinvent_3.8cutoff",
            source_version="3.8",
            key='XXXXXXXXXXXXXXXXXX(I erased it)',
            external_scenarios=[
                ammonia, # <-- list datapackages here
            ] 
        )

ndb.update_all()

**Comment by romainsacchi** [comment] 2022-10-21 10:20
It seems the ammonia scenarios are not really compatible with the `update_fuels()` function -- which is automatically run when you do `update_all()`.
The issue is that the ammonia scenario needs a hydrogen dataset which has previously been renamed by `update_fuels()`, hence it cannot find it.
I will put a restriction on using the ammonia scenario together with `update_fuels()`. But in the long-term, I need to fix this.

So, you could instead do:

```
ndb = NewDatabase(
        scenarios = [
            {"model":"remind", "pathway":"SSP2-PkBudg1150", "year":2050, "exclude": ["update_fuels"]},
        ],        
        source_db="ecoinvent_3.8cutoff",
        source_version="3.8",
        key='XXXXXXXXXXXXXXXXXX(I erased it)',
        external_scenarios=[
            ammonia, # <-- list datapackages here
        ] 
 )
ndb.update_all()
```

This should perform everything except for the fuels integration.

**Comment by marcosdbw** [comment] 2022-10-21 10:59
Ok, great. I will test it again without update_fuels(). Thanks, @romainsacchi

**Comment by marcosdbw** [comment] 2022-10-21 11:55
It worked without update_fuels() ! thanks again

**Comment by romainsacchi** [comment] 2022-10-21 12:02
I'll leave the issue open to remind me to fix it.

**Comment by romainsacchi** [comment] 2022-10-22 09:22
Hi @marcosdbw ,
the issue is now fixed.
You can run the ammonia scenarios together with `update_fuels()`.

**Closed as completed by romainsacchi** 2022-10-22 09:22 UTC

**Comment by marcosdbw** [comment] 2022-10-22 10:47
Hi @romainsacchi . Yes, it worked here as well. Thank you!
